FROM cgr.dev/chainguard/wolfi-base:latest

ARG TARGETARCH

WORKDIR /app

RUN apk add --no-cache libstdc++

COPY static static
COPY templates templates
COPY builds/$TARGETARCH/release/bgcat .

EXPOSE 8000

VOLUME /app/data

USER nobody

ENTRYPOINT ["/app/bgcat"]
